sudo: required
language: bash

before_install:
        - sudo apt-get update -q
        - export scversion="stable" # or "v0.4.7", or "latest"
       
        - /usr/bin/shellcheck --version
        - sed -i 's/\r//g' test-1.sh
         


       
       

       

after_failure:
        - id
        - pwd
        - df -h
        
        

notifications:
          email:
                  on_success: never
