language: bash

before_install:
  - sudo apt-get update && sudo apt-get install -y shellcheck

script:
  - ls -l
  - bash test-11.sh
  - ls -l
  - pwd
  - cat file
  - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z"
  - sudo apt install p7zip-full
  - 7z x web_log.tsv.7z
 
notifications:
  email:
    on_success: never
